CREATE TABLE "ih_meta" (
	"ID"	INTEGER,
	"TEST_ID"	TEXT NOT NULL CHECK(length("TEST_ID") <= 255),
	"IMG_UUID"	TEXT UNIQUE,
	"HTML_IMG_ID"	TEXT,
	"FILE_NAME"	TEXT NOT NULL CHECK(length("FILE_NAME") <= 255),
	"FILE_HASH"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);

CREATE TABLE "ih_content" (
	"FILE_IH_META_ID"	INTEGER,
	"FILE_DATA"	BLOB NOT NULL,
	"FILE_B64_DATA"	TEXT NOT NULL,
	FOREIGN KEY("FILE_IH_META_ID") REFERENCES "ih_meta"("ID") ON DELETE CASCADE,
	PRIMARY KEY("FILE_IH_META_ID")
);

CREATE TABLE "ih_logs" (
	"LOG_ID"	INTEGER,
	"TEST_ID"	TEXT NOT NULL,
	"STATUS"	TEXT,
	"RESPONSE_TIME_MS"	INTEGER,
	"EXECUTED_AT"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"ERROR_MSG"	TEXT,
	"FILE_IH_META_ID"	INTEGER NOT NULL,
	"IMG_UUID"	TEXT,
	FOREIGN KEY("FILE_IH_META_ID") REFERENCES "ih_meta"("ID") ON DELETE CASCADE,
	PRIMARY KEY("LOG_ID" AUTOINCREMENT)
);